spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/storedb
    username: postgres
    password: adm
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true
    clean-disabled: true  # Prevents accidenta

server:
  port: 8080
  servlet:
    context-path: /

# JWT Configuration
jwt:
  secret: 64cc63079da9a5dfd1ce20c65e2cee9ae5c7a79112ecf32c0b77e7c4c4c2a52b
  expiration: 86400000  # 24 hours in milliseconds

# Logging Configuration
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.boot.autoconfigure.security: INFO
    com.store: DEBUG

# Swagger Documentation
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha