version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: storedb
    restart: always
    environment:
      POSTGRES_DB: storedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  springboot-app:
    build: .
    container_name: springboot-store
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/storedb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: adm
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SERVER_PORT: 8080
      SERVER_SERVLET_CONTEXT_PATH: /
      SPRING_SECURITY_USER_NAME: admin
      SPRING_SECURITY_USER_PASSWORD: admin
      SPRING_SECURITY_USER_ROLES: ADMIN
      JWT_SECRET: 64cc63079da9a5dfd1ce20c65e2cee9ae5c7a79112ecf32c0b77e7c4c4c2a52b
      JWT_EXPIRATION: 86400000
    networks:
      - springnet

volumes:
  postgres_data:

networks:
  springnet:
    driver: bridge
